name: "docker_build"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  docker_build:
    name: docker build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
