name: "docker_build"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  docker_build:
    name: docker build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        rosdistro: ["iron", "humble", "rolling"]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/bake-action@v3
        with:
          push: true
          workdir: .
          files: |
            ./docker-bake.hcl
          targets: |
            ${{ matrix.rosdistro }}
